import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DW Ecommerce",
  description: "Generated by create next app",
  icons: {
    icon: "/logooo.jpg",
  },
};

const config = {
  domain: process.env.AUTH0_DOMAIN || "dev-de2xc48ju2qxy2fh.us.auth0.com",
  clientId: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  scope: "openid profile email",
  issuerBaseURL:
    process.env.ISSUER_BASE_URL || "https://dev-de2xc48ju2qxy2fh.us.auth0.com",
  redirectUri: "/api/auth/callback",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider {...config}>
        <body className={inter.className}>
          <div className="min-h-screen flex flex-col">
            <Navbar />
            <main className="flex flex-grow justify-center py-5 ">
              {children}{" "}
            </main>
            <Footer />
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
